
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.SQLException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author danie
 */
public class ADM_ListEmp extends javax.swing.JFrame {

    Connection conn;

    /**
     * Creates new form ADM_ListEmp
     */
    public ADM_ListEmp() {
        initComponents();

        this.conn = javaconnect.ConnectDb();  // Only once

        setLocationRelativeTo(null);

        setResizable(false); // ✅ Prevents window resizing
        setExtendedState(JFrame.NORMAL); // ✅ Ensures window stays at default state

        ImageIcon logo = new ImageIcon("C:\\Users\\danie\\Downloads\\PS_FinalLogo.png"); // ✅ Update with correct file location
        setIconImage(logo.getImage());

        setTitle("Payroll Swift"); // ✅ Custom window title

        loadUserIDs();
        list_savechanges.setEnabled(false);
        list_modify.setEnabled(false);
        list_delete.setEnabled(false);
        navigation_viewaccount.setEnabled(false);
    }

    private void loadUserIDs() {
        try {
            Class.forName("org.sqlite.JDBC");  // Load SQLite driver
            String url = "jdbc:sqlite:C:/Users/danie/OneDrive/Documents/NetBeansProjects/PayrollModule_2_Copy/Payroll.db";
            Connection conn = DriverManager.getConnection(url);

            String sql = "SELECT UserID FROM ListEmpAccounts ORDER BY CAST(SUBSTR(UserID, 4) AS INTEGER) ASC";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            list_useridcombobox.removeAllItems(); // Clear old items

            while (rs.next()) {
                list_useridcombobox.addItem(rs.getString("UserID"));
            }

            rs.close();
            pst.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error loading UserIDs: " + e.getMessage());
        }
    }

    private void disableAllListFields() {
        list_firstname.setEditable(false);
        list_lastname.setEditable(false);
        list_sex.setEnabled(false);
        list_dateofbirth.setEditable(false);
        list_civilstatus.setEnabled(false);
        list_address.setEditable(false);
        list_contactnumber.setEditable(false);
        list_emailaddress.setEditable(false);
        list_month.setEnabled(false);
        list_year.setEnabled(false);
        list_bankname.setEnabled(false);
        list_accountnumber.setEditable(false);
        list_accountname.setEditable(false);
        list_governmentID.setEnabled(false);
        list_govidnumber.setEditable(false);
        list_password.setEditable(false);
        list_department.setEnabled(false);
        list_jobposition.setEnabled(false);
        list_empstatus.setEnabled(false);
        list_datehired.setEditable(false);
        list_managername.setEditable(false);
        list_dailyrate.setEditable(false);
        list_hourlyrate.setEditable(false);
        list_perminuterate.setEditable(false);
        list_basicsalary.setEditable(false);

    }

    private void clearAllFields() {
        list_firstname.setText("");
        list_lastname.setText("");
        list_dateofbirth.setText("");
        list_address.setText("");
        list_contactnumber.setText("");
        list_emailaddress.setText("");
        list_accountnumber.setText("");
        list_accountname.setText("");
        list_govidnumber.setText("");
        list_password.setText("");
        list_datehired.setText("");
        list_managername.setText("");
        list_dailyrate.setText("");
        list_hourlyrate.setText("");
        list_perminuterate.setText("");
        list_basicsalary.setText("");

        list_sex.setSelectedIndex(-1);
        list_civilstatus.setSelectedIndex(-1);
        list_month.setSelectedIndex(-1);
        list_year.setSelectedIndex(-1);
        list_bankname.setSelectedIndex(-1);
        list_governmentID.setSelectedIndex(-1);
        list_department.setSelectedIndex(-1);
        list_jobposition.setSelectedIndex(-1);
        list_empstatus.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        left_panel = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        credits = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        navigation_payrollmodule = new javax.swing.JLabel();
        navigation_createaccount = new javax.swing.JLabel();
        navigation_viewaccount = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        useridTXT_LABEL = new javax.swing.JLabel();
        firstnameTXT_LABEL = new javax.swing.JLabel();
        lastnameTXT_LABEL = new javax.swing.JLabel();
        sexTXT_LABEL = new javax.swing.JLabel();
        deptTXT_LABEL = new javax.swing.JLabel();
        jobpositionTXT_LABEL = new javax.swing.JLabel();
        empstatusTXT_LABEL = new javax.swing.JLabel();
        list_empstatus = new javax.swing.JComboBox<>();
        list_jobposition = new javax.swing.JComboBox<>();
        list_department = new javax.swing.JComboBox<>();
        list_sex = new javax.swing.JComboBox<>();
        list_lastname = new javax.swing.JTextField();
        list_firstname = new javax.swing.JTextField();
        bankDetail_LABEL = new javax.swing.JLabel();
        list_month = new javax.swing.JComboBox<>();
        monthTXT_LABEL = new javax.swing.JLabel();
        list_year = new javax.swing.JComboBox<>();
        yearTXT_LABEL = new javax.swing.JLabel();
        banknameTXT_LABEL = new javax.swing.JLabel();
        list_bankname = new javax.swing.JComboBox<>();
        list_accountnumber = new javax.swing.JTextField();
        accountnumberTXT_LABEL = new javax.swing.JLabel();
        accountnameTXT_LABEL = new javax.swing.JLabel();
        list_accountname = new javax.swing.JTextField();
        list_governmentID = new javax.swing.JComboBox<>();
        govIDTXT_LABEL = new javax.swing.JLabel();
        govidnumberTXT_LABEL = new javax.swing.JLabel();
        list_govidnumber = new javax.swing.JTextField();
        list_dateofbirth = new javax.swing.JTextField();
        list_address = new javax.swing.JTextField();
        list_contactnumber = new javax.swing.JTextField();
        list_emailaddress = new javax.swing.JTextField();
        sexTXT_LABEL1 = new javax.swing.JLabel();
        sexTXT_LABEL2 = new javax.swing.JLabel();
        sexTXT_LABEL3 = new javax.swing.JLabel();
        sexTXT_LABEL4 = new javax.swing.JLabel();
        sexTXT_LABEL5 = new javax.swing.JLabel();
        list_civilstatus = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        list_datehired = new javax.swing.JTextField();
        sexTXT_LABEL6 = new javax.swing.JLabel();
        list_managername = new javax.swing.JTextField();
        sexTXT_LABEL7 = new javax.swing.JLabel();
        currenttimee = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        list_dailyrate = new javax.swing.JTextField();
        dailyrateTXT_LABEL = new javax.swing.JLabel();
        hourlyrateTXT_LABEL = new javax.swing.JLabel();
        list_hourlyrate = new javax.swing.JTextField();
        list_perminuterate = new javax.swing.JTextField();
        perminuterateTXT_LABEL = new javax.swing.JLabel();
        list_basicsalary = new javax.swing.JTextField();
        perminuterateTXT_LABEL1 = new javax.swing.JLabel();
        list_modify = new javax.swing.JButton();
        list_delete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        list_savechanges = new javax.swing.JButton();
        return_banktransferpage = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        list_password = new javax.swing.JTextField();
        govidnumberTXT_LABEL1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        notes = new javax.swing.JLabel();
        list_useridcombobox = new javax.swing.JComboBox<>();
        list_generate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1043, 862));
        setPreferredSize(new java.awt.Dimension(1043, 821));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1043, 987));

        left_panel.setBackground(new java.awt.Color(0, 34, 71));
        left_panel.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AYROLL WIFT (2) (3).png"))); // NOI18N
        jLabel4.setText(" ");

        credits.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        credits.setForeground(new java.awt.Color(255, 255, 255));
        credits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        credits.setText("© 2025 Payroll Swift");

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        navigation_payrollmodule.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        navigation_payrollmodule.setForeground(new java.awt.Color(255, 255, 255));
        navigation_payrollmodule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image (5) (1).png"))); // NOI18N
        navigation_payrollmodule.setText("  Payment History");
        navigation_payrollmodule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navigation_payrollmoduleMouseClicked(evt);
            }
        });

        navigation_createaccount.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        navigation_createaccount.setForeground(new java.awt.Color(255, 255, 255));
        navigation_createaccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image (6).png"))); // NOI18N
        navigation_createaccount.setText("  Create Employee Account");
        navigation_createaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navigation_createaccountMouseClicked(evt);
            }
        });

        navigation_viewaccount.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        navigation_viewaccount.setForeground(new java.awt.Color(255, 255, 255));
        navigation_viewaccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image (7).png"))); // NOI18N
        navigation_viewaccount.setText("  View Employee Account");
        navigation_viewaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navigation_viewaccountMouseClicked(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout left_panelLayout = new javax.swing.GroupLayout(left_panel);
        left_panel.setLayout(left_panelLayout);
        left_panelLayout.setHorizontalGroup(
            left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, left_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(left_panelLayout.createSequentialGroup()
                .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(navigation_createaccount, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(left_panelLayout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(credits, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(left_panelLayout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(navigation_payrollmodule, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(navigation_viewaccount, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(left_panelLayout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(left_panelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        left_panelLayout.setVerticalGroup(
            left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(left_panelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(navigation_payrollmodule)
                .addGap(27, 27, 27)
                .addComponent(navigation_createaccount)
                .addGap(26, 26, 26)
                .addComponent(navigation_viewaccount)
                .addGap(36, 36, 36)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 435, Short.MAX_VALUE)
                .addComponent(credits)
                .addGap(22, 22, 22))
            .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(left_panelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 411, Short.MAX_VALUE)))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Personal Data");

        useridTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        useridTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        useridTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        useridTXT_LABEL.setText("User ID");

        firstnameTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        firstnameTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        firstnameTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        firstnameTXT_LABEL.setText("First Name");

        lastnameTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        lastnameTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lastnameTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        lastnameTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lastnameTXT_LABEL.setText("Last Name");

        sexTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        sexTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        sexTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        sexTXT_LABEL.setText("Sex");

        deptTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        deptTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        deptTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        deptTXT_LABEL.setText("Department");

        jobpositionTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        jobpositionTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jobpositionTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        jobpositionTXT_LABEL.setText("Job Position");

        empstatusTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        empstatusTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        empstatusTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        empstatusTXT_LABEL.setText("Emp. Status");

        list_empstatus.setBackground(new java.awt.Color(255, 255, 255));
        list_empstatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        list_empstatus.setForeground(new java.awt.Color(0, 0, 51));
        list_empstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full-Time", "Part-Time", "Probationary", "Contractual" }));
        list_empstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_empstatusActionPerformed(evt);
            }
        });

        list_jobposition.setBackground(new java.awt.Color(255, 255, 255));
        list_jobposition.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        list_jobposition.setForeground(new java.awt.Color(0, 0, 51));
        list_jobposition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software Developer", "Front-End Developer", "Back-End Developer", "Full-Stack Developer", "Mobile App Developer", "UI/UX Designer", "System Administrator", "Network Administrator", "Cybersecurity Analyst", "Security Engineer", "Database Administrator", "Machine Learning Engineer", "AI Engineer", "Project Manager" }));
        list_jobposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_jobpositionActionPerformed(evt);
            }
        });

        list_department.setBackground(new java.awt.Color(255, 255, 255));
        list_department.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        list_department.setForeground(new java.awt.Color(0, 0, 51));
        list_department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software Development", "UI/UX and Design", "IT Infrastructure", "Cybersecurity", "Data and Analytics", "AI and Machine Learning" }));
        list_department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_departmentActionPerformed(evt);
            }
        });

        list_sex.setBackground(new java.awt.Color(255, 255, 255));
        list_sex.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        list_sex.setForeground(new java.awt.Color(0, 0, 51));
        list_sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        list_sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_sexActionPerformed(evt);
            }
        });

        list_lastname.setBackground(new java.awt.Color(255, 255, 255));
        list_lastname.setForeground(new java.awt.Color(0, 0, 0));

        list_firstname.setBackground(new java.awt.Color(255, 255, 255));
        list_firstname.setForeground(new java.awt.Color(0, 0, 0));

        bankDetail_LABEL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bankDetail_LABEL.setForeground(new java.awt.Color(0, 0, 51));
        bankDetail_LABEL.setText("Bank Detail");

        list_month.setBackground(new java.awt.Color(255, 255, 255));
        list_month.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        list_month.setForeground(new java.awt.Color(0, 0, 51));
        list_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "May", "June", "July", "August", "September", "October", "November", "December" }));
        list_month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_monthActionPerformed(evt);
            }
        });

        monthTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        monthTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        monthTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        monthTXT_LABEL.setText("Month");

        list_year.setBackground(new java.awt.Color(255, 255, 255));
        list_year.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        list_year.setForeground(new java.awt.Color(0, 0, 51));
        list_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2025", "2026", "2027", "2028", "2029", "2030" }));
        list_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_yearActionPerformed(evt);
            }
        });

        yearTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        yearTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        yearTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        yearTXT_LABEL.setText("Year");

        banknameTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        banknameTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        banknameTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        banknameTXT_LABEL.setText("Bank Name");

        list_bankname.setBackground(new java.awt.Color(255, 255, 255));
        list_bankname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        list_bankname.setForeground(new java.awt.Color(0, 0, 51));
        list_bankname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BDO Unibank", "Metrobank", "Bank of the Philippine Islands (BPI)", "Philippine National Bank (PNB)", "Land Bank of the Philippines (LandBank)", "Security Bank", "China Banking Corporation (China Bank)", "UnionBank of the Philippines", "EastWest Bank", "Rizal Commercial Banking Corporation (RCBC)", "Development Bank of the Philippines (DBP)", "UCPB (United Coconut Planters Bank)", "Philippine Savings Bank (PSBank)", "Maybank Philippines", "Standard Chartered Bank Philippines" }));
        list_bankname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_banknameActionPerformed(evt);
            }
        });

        list_accountnumber.setBackground(new java.awt.Color(255, 255, 255));
        list_accountnumber.setForeground(new java.awt.Color(0, 0, 0));

        accountnumberTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        accountnumberTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        accountnumberTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        accountnumberTXT_LABEL.setText("Account Number");

        accountnameTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        accountnameTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        accountnameTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        accountnameTXT_LABEL.setText("Account Name");

        list_accountname.setBackground(new java.awt.Color(255, 255, 255));
        list_accountname.setForeground(new java.awt.Color(0, 0, 0));

        list_governmentID.setBackground(new java.awt.Color(255, 255, 255));
        list_governmentID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        list_governmentID.setForeground(new java.awt.Color(0, 0, 51));
        list_governmentID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIN", "SSS", "PhilHealth", "Pag-IBIG" }));
        list_governmentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_governmentIDActionPerformed(evt);
            }
        });

        govIDTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        govIDTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        govIDTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        govIDTXT_LABEL.setText("Government ID");

        govidnumberTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        govidnumberTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        govidnumberTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        govidnumberTXT_LABEL.setText("Gov. ID Number");

        list_govidnumber.setBackground(new java.awt.Color(255, 255, 255));
        list_govidnumber.setForeground(new java.awt.Color(0, 0, 0));

        list_dateofbirth.setBackground(new java.awt.Color(255, 255, 255));
        list_dateofbirth.setForeground(new java.awt.Color(0, 0, 0));
        list_dateofbirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_dateofbirthActionPerformed(evt);
            }
        });

        list_address.setBackground(new java.awt.Color(255, 255, 255));
        list_address.setForeground(new java.awt.Color(0, 0, 0));

        list_contactnumber.setBackground(new java.awt.Color(255, 255, 255));
        list_contactnumber.setForeground(new java.awt.Color(0, 0, 0));

        list_emailaddress.setBackground(new java.awt.Color(255, 255, 255));
        list_emailaddress.setForeground(new java.awt.Color(0, 0, 0));

        sexTXT_LABEL1.setBackground(new java.awt.Color(0, 0, 0));
        sexTXT_LABEL1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        sexTXT_LABEL1.setForeground(new java.awt.Color(0, 0, 0));
        sexTXT_LABEL1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        sexTXT_LABEL1.setText("Date of Birth");

        sexTXT_LABEL2.setBackground(new java.awt.Color(0, 0, 0));
        sexTXT_LABEL2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        sexTXT_LABEL2.setForeground(new java.awt.Color(0, 0, 0));
        sexTXT_LABEL2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        sexTXT_LABEL2.setText("Civil Status");

        sexTXT_LABEL3.setBackground(new java.awt.Color(0, 0, 0));
        sexTXT_LABEL3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        sexTXT_LABEL3.setForeground(new java.awt.Color(0, 0, 0));
        sexTXT_LABEL3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        sexTXT_LABEL3.setText("Address");

        sexTXT_LABEL4.setBackground(new java.awt.Color(0, 0, 0));
        sexTXT_LABEL4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        sexTXT_LABEL4.setForeground(new java.awt.Color(0, 0, 0));
        sexTXT_LABEL4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        sexTXT_LABEL4.setText("Contact Number");

        sexTXT_LABEL5.setBackground(new java.awt.Color(0, 0, 0));
        sexTXT_LABEL5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        sexTXT_LABEL5.setForeground(new java.awt.Color(0, 0, 0));
        sexTXT_LABEL5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        sexTXT_LABEL5.setText("Email Address");

        list_civilstatus.setBackground(new java.awt.Color(255, 255, 255));
        list_civilstatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        list_civilstatus.setForeground(new java.awt.Color(0, 0, 51));
        list_civilstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Widowed", "Separated", "Annulled" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Employment Information");

        list_datehired.setBackground(new java.awt.Color(255, 255, 255));
        list_datehired.setForeground(new java.awt.Color(0, 0, 0));

        sexTXT_LABEL6.setBackground(new java.awt.Color(0, 0, 0));
        sexTXT_LABEL6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        sexTXT_LABEL6.setForeground(new java.awt.Color(0, 0, 0));
        sexTXT_LABEL6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        sexTXT_LABEL6.setText("Date Hired");

        list_managername.setBackground(new java.awt.Color(255, 255, 255));
        list_managername.setForeground(new java.awt.Color(0, 0, 0));

        sexTXT_LABEL7.setBackground(new java.awt.Color(0, 0, 0));
        sexTXT_LABEL7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        sexTXT_LABEL7.setForeground(new java.awt.Color(0, 0, 0));
        sexTXT_LABEL7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        sexTXT_LABEL7.setText("Manager Name");

        currenttimee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        currenttimee.setForeground(new java.awt.Color(0, 0, 0));
        currenttimee.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Computed Rates");

        list_dailyrate.setBackground(new java.awt.Color(255, 255, 255));
        list_dailyrate.setForeground(new java.awt.Color(0, 0, 0));
        list_dailyrate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_dailyrateActionPerformed(evt);
            }
        });

        dailyrateTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        dailyrateTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        dailyrateTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        dailyrateTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        dailyrateTXT_LABEL.setText("Daily Rate");

        hourlyrateTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        hourlyrateTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        hourlyrateTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        hourlyrateTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        hourlyrateTXT_LABEL.setText("Hourly Rate");

        list_hourlyrate.setBackground(new java.awt.Color(255, 255, 255));
        list_hourlyrate.setForeground(new java.awt.Color(0, 0, 0));

        list_perminuterate.setBackground(new java.awt.Color(255, 255, 255));
        list_perminuterate.setForeground(new java.awt.Color(0, 0, 0));
        list_perminuterate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_perminuterateActionPerformed(evt);
            }
        });

        perminuterateTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        perminuterateTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        perminuterateTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        perminuterateTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        perminuterateTXT_LABEL.setText("Per Minute Rate");

        list_basicsalary.setBackground(new java.awt.Color(255, 255, 255));
        list_basicsalary.setForeground(new java.awt.Color(0, 0, 0));

        perminuterateTXT_LABEL1.setBackground(new java.awt.Color(0, 0, 0));
        perminuterateTXT_LABEL1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        perminuterateTXT_LABEL1.setForeground(new java.awt.Color(0, 0, 0));
        perminuterateTXT_LABEL1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        perminuterateTXT_LABEL1.setText("Basic Salary");

        list_modify.setBackground(new java.awt.Color(0, 0, 51));
        list_modify.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        list_modify.setForeground(new java.awt.Color(255, 255, 255));
        list_modify.setText("Modify");
        list_modify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_modifyMouseClicked(evt);
            }
        });
        list_modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_modifyActionPerformed(evt);
            }
        });

        list_delete.setBackground(new java.awt.Color(51, 0, 0));
        list_delete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        list_delete.setForeground(new java.awt.Color(255, 255, 255));
        list_delete.setText("Delete");
        list_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_deleteMouseClicked(evt);
            }
        });
        list_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_deleteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Update Account");

        list_savechanges.setBackground(new java.awt.Color(0, 0, 51));
        list_savechanges.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        list_savechanges.setForeground(new java.awt.Color(255, 255, 255));
        list_savechanges.setText("Save Changes");
        list_savechanges.setActionCommand("Save");
        list_savechanges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_savechangesMouseClicked(evt);
            }
        });
        list_savechanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_savechangesActionPerformed(evt);
            }
        });

        return_banktransferpage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/replay (1).png"))); // NOI18N
        return_banktransferpage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                return_banktransferpageMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("VIEW EMPLOYEE ACCOUNT");

        list_password.setBackground(new java.awt.Color(255, 255, 255));
        list_password.setForeground(new java.awt.Color(0, 0, 0));
        list_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_passwordActionPerformed(evt);
            }
        });

        govidnumberTXT_LABEL1.setBackground(new java.awt.Color(0, 0, 0));
        govidnumberTXT_LABEL1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        govidnumberTXT_LABEL1.setForeground(new java.awt.Color(0, 0, 0));
        govidnumberTXT_LABEL1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        govidnumberTXT_LABEL1.setText("Account Password");

        notes.setBackground(new java.awt.Color(0, 0, 0));
        notes.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        notes.setForeground(new java.awt.Color(0, 0, 0));
        notes.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        notes.setText("Note: Review employee info and role before modifying or deleting the account.");

        list_useridcombobox.setBackground(new java.awt.Color(255, 255, 255));
        list_useridcombobox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        list_useridcombobox.setForeground(new java.awt.Color(0, 0, 51));
        list_useridcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_useridcomboboxActionPerformed(evt);
            }
        });

        list_generate.setBackground(new java.awt.Color(0, 0, 51));
        list_generate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        list_generate.setForeground(new java.awt.Color(255, 255, 255));
        list_generate.setText("Generate");
        list_generate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_generateMouseClicked(evt);
            }
        });
        list_generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_generateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(deptTXT_LABEL)
                                    .addComponent(jobpositionTXT_LABEL)
                                    .addComponent(empstatusTXT_LABEL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(list_department, 0, 1, Short.MAX_VALUE)
                                    .addComponent(list_jobposition, 0, 1, Short.MAX_VALUE)
                                    .addComponent(list_empstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sexTXT_LABEL6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexTXT_LABEL7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(list_datehired, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(list_managername, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(list_savechanges, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(perminuterateTXT_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(perminuterateTXT_LABEL1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hourlyrateTXT_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dailyrateTXT_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(list_dailyrate, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(list_hourlyrate)
                                    .addComponent(list_perminuterate)
                                    .addComponent(list_basicsalary))))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(list_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(list_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(left_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(return_banktransferpage, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(useridTXT_LABEL)
                                            .addComponent(firstnameTXT_LABEL)
                                            .addComponent(sexTXT_LABEL)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lastnameTXT_LABEL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(sexTXT_LABEL2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(sexTXT_LABEL4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(sexTXT_LABEL5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(sexTXT_LABEL1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sexTXT_LABEL3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(list_dateofbirth)
                                                .addComponent(list_lastname)
                                                .addComponent(list_firstname)
                                                .addComponent(list_address)
                                                .addComponent(list_contactnumber, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(list_emailaddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(list_civilstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(list_sex, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(list_useridcombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(list_generate))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel2)))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(36, 36, 36)
                                                    .addComponent(bankDetail_LABEL))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                    .addGap(36, 36, 36)
                                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(banknameTXT_LABEL)
                                                                        .addComponent(yearTXT_LABEL)))
                                                                .addComponent(accountnumberTXT_LABEL, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(monthTXT_LABEL, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(govidnumberTXT_LABEL, javax.swing.GroupLayout.Alignment.TRAILING))
                                                            .addComponent(govIDTXT_LABEL, javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(accountnameTXT_LABEL, javax.swing.GroupLayout.Alignment.TRAILING))
                                                        .addComponent(govidnumberTXT_LABEL1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(list_password, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(list_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(list_accountname)
                                                            .addComponent(list_accountnumber)
                                                            .addComponent(list_bankname, 0, 1, Short.MAX_VALUE)
                                                            .addComponent(list_month, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(list_govidnumber, javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(list_governmentID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addGap(17, 17, 17))
                                        .addComponent(currenttimee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(notes)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(return_banktransferpage, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bankDetail_LABEL)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(monthTXT_LABEL)
                                .addComponent(list_month, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(useridTXT_LABEL)
                                .addComponent(list_useridcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(list_generate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(list_year, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearTXT_LABEL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(list_bankname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(banknameTXT_LABEL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(list_accountnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accountnumberTXT_LABEL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(list_accountname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accountnameTXT_LABEL)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(list_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstnameTXT_LABEL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(list_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastnameTXT_LABEL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(list_sex, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexTXT_LABEL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(list_dateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexTXT_LABEL1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(list_governmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(govIDTXT_LABEL)
                        .addComponent(sexTXT_LABEL2))
                    .addComponent(list_civilstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(list_govidnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(govidnumberTXT_LABEL)
                    .addComponent(list_address, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexTXT_LABEL3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(list_contactnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sexTXT_LABEL4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(currenttimee, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(list_emailaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sexTXT_LABEL5))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(list_password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(govidnumberTXT_LABEL1)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(list_department, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deptTXT_LABEL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(list_jobposition, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jobpositionTXT_LABEL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(list_empstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empstatusTXT_LABEL)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(list_dailyrate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dailyrateTXT_LABEL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(list_hourlyrate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hourlyrateTXT_LABEL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(list_perminuterate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(perminuterateTXT_LABEL))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(list_datehired, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexTXT_LABEL6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(list_managername, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexTXT_LABEL7)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(list_basicsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(perminuterateTXT_LABEL1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(list_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(list_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(list_savechanges, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(notes)
                .addGap(191, 191, 191))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(left_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void list_generateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_generateMouseClicked
        list_modify.setEnabled(true);
        list_delete.setEnabled(true);

        String selectedUserID = (String) list_useridcombobox.getSelectedItem();

        if (selectedUserID == null || selectedUserID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select a UserID.");
            return;
        }

        try {
            // Load SQLite driver
            Class.forName("org.sqlite.JDBC");

            // Open a new connection
            String url = "jdbc:sqlite:C:/Users/danie/OneDrive/Documents/NetBeansProjects/PayrollModule_2_Copy/Payroll.db";
            Connection conn = DriverManager.getConnection(url);

            // Prepare SQL query
            String sql = "SELECT * FROM ListEmpAccounts WHERE UserID = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, selectedUserID);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                list_firstname.setText(rs.getString("FirstName"));
                list_lastname.setText(rs.getString("LastName"));
                list_sex.setSelectedItem(rs.getString("Sex"));
                list_dateofbirth.setText(rs.getString("DOB"));
                list_civilstatus.setSelectedItem(rs.getString("CivilStatus"));
                list_address.setText(rs.getString("Address"));
                list_contactnumber.setText(rs.getString("ContactNum"));
                list_emailaddress.setText(rs.getString("Email"));
                list_month.setSelectedItem(rs.getString("Month"));
                list_year.setSelectedItem(rs.getString("Year"));
                list_bankname.setSelectedItem(rs.getString("BankName"));
                list_accountnumber.setText(rs.getString("AccNum"));
                list_accountname.setText(rs.getString("AccName"));
                list_governmentID.setSelectedItem(rs.getString("GovID"));
                list_govidnumber.setText(rs.getString("GovIDNum"));
                list_password.setText(rs.getString("Password"));
                list_department.setSelectedItem(rs.getString("Dept"));
                list_jobposition.setSelectedItem(rs.getString("JobPos"));
                list_empstatus.setSelectedItem(rs.getString("EmpStatus"));
                list_datehired.setText(rs.getString("DateHired"));
                list_managername.setText(rs.getString("ManagerName"));
                list_dailyrate.setText(rs.getString("DailyRate"));
                list_hourlyrate.setText(rs.getString("HourlyRate"));
                list_perminuterate.setText(rs.getString("PerMinuteRate"));
                list_basicsalary.setText(rs.getString("BasicSalary"));

                disableAllListFields();  // ✅ Disable all fields after filling
            } else {
                JOptionPane.showMessageDialog(null, "No data found for selected UserID.");
            }

            rs.close();
            pst.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error generating data: " + e.getMessage());
        }
    }//GEN-LAST:event_list_generateMouseClicked

    private void list_useridcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_useridcomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_useridcomboboxActionPerformed

    private void list_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_passwordActionPerformed

    private void return_banktransferpageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_return_banktransferpageMouseClicked
        this.dispose(); // ✅ Close ADM_AddEMP
        new ADM_PayrollModule().setVisible(true); // ✅ Open ADM_PayrollModule
        ADM_AddEMP addEmp = new ADM_AddEMP();
    }//GEN-LAST:event_return_banktransferpageMouseClicked

    private void list_savechangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_savechangesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_savechangesActionPerformed

    private void list_savechangesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_savechangesMouseClicked
        String selectedUserID = (String) list_useridcombobox.getSelectedItem();

        int confirm = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to save the changes?",
                "Confirm Save",
                JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) {
            return; // User canceled save
        }

        try {
            Class.forName("org.sqlite.JDBC");
            String url = "jdbc:sqlite:C:/Users/danie/OneDrive/Documents/NetBeansProjects/PayrollModule_2_Copy/Payroll.db";
            Connection conn = DriverManager.getConnection(url);

            // First update: ListEmpAccounts
            String sql = "UPDATE ListEmpAccounts SET "
                    + "FirstName = ?, LastName = ?, Sex = ?, DOB = ?, CivilStatus = ?, "
                    + "Address = ?, ContactNum = ?, Email = ?, Month = ?, Year = ?, BankName = ?, "
                    + "AccNum = ?, AccName = ?, GovID = ?, GovIDNum = ?, Password = ?, Dept = ?, "
                    + "JobPos = ?, EmpStatus = ?, DateHired = ?, ManagerName = ?, DailyRate = ?, "
                    + "HourlyRate = ?, PerMinuteRate = ?, BasicSalary = ? "
                    + "WHERE UserID = ?";

            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, list_firstname.getText());
            pst.setString(2, list_lastname.getText());
            pst.setString(3, (String) list_sex.getSelectedItem());
            pst.setString(4, list_dateofbirth.getText());
            pst.setString(5, (String) list_civilstatus.getSelectedItem());
            pst.setString(6, list_address.getText());
            pst.setString(7, list_contactnumber.getText());
            pst.setString(8, list_emailaddress.getText());
            pst.setString(9, (String) list_month.getSelectedItem());
            pst.setString(10, (String) list_year.getSelectedItem());
            pst.setString(11, (String) list_bankname.getSelectedItem());
            pst.setString(12, list_accountnumber.getText());
            pst.setString(13, list_accountname.getText());
            pst.setString(14, (String) list_governmentID.getSelectedItem());
            pst.setString(15, list_govidnumber.getText());
            pst.setString(16, list_password.getText());
            pst.setString(17, (String) list_department.getSelectedItem());
            pst.setString(18, (String) list_jobposition.getSelectedItem());
            pst.setString(19, (String) list_empstatus.getSelectedItem());
            pst.setString(20, list_datehired.getText());
            pst.setString(21, list_managername.getText());
            pst.setString(22, list_dailyrate.getText());
            pst.setString(23, list_hourlyrate.getText());
            pst.setString(24, list_perminuterate.getText());
            pst.setString(25, list_basicsalary.getText());
            pst.setString(26, selectedUserID); // WHERE clause

            int updated = pst.executeUpdate();

            if (updated > 0) {
                // Second update: PersonalData table to update NewPass column
                String sql2 = "UPDATE PersonalData SET NewPass = ? WHERE UserID = ?";
                PreparedStatement pst2 = conn.prepareStatement(sql2);
                pst2.setString(1, list_password.getText());
                pst2.setString(2, selectedUserID);
                pst2.executeUpdate();
                pst2.close();

                JOptionPane.showMessageDialog(null, "Employee information updated successfully.");

                // Disable save button and fields again
                list_savechanges.setEnabled(false);
                disableAllListFields();
            } else {
                JOptionPane.showMessageDialog(null, "No update performed. Please check the data.");
            }

            pst.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error saving changes: " + e.getMessage());
        }
    }//GEN-LAST:event_list_savechangesMouseClicked

    private void list_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_deleteMouseClicked
        String selectedUserID = (String) list_useridcombobox.getSelectedItem();

        if (selectedUserID == null || selectedUserID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select a UserID to delete.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to delete all records related to UserID: " + selectedUserID + "?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        Connection conn = null;

        try {
            Class.forName("org.sqlite.JDBC");
            String url = "jdbc:sqlite:C:/Users/danie/OneDrive/Documents/NetBeansProjects/PayrollModule_2_Copy/Payroll.db";
            conn = DriverManager.getConnection(url);
            conn.setAutoCommit(false); // Start transaction

            // All tables where UserID-related records should be deleted
            String[] tables = {
                "ListEmpAccounts",
                "PersonalData",
                "SentSalary",
                "EWalletTable",
                "EmploymentInformation",
                "EmployeeIncome",
                "EWallet_Cash",
                "ComputedRates",
                "BankTransfer",
                "BankDetails",
                "ADM_SalarySummary",
                "PaySlip",
                "PayrollHistory"
            };

            for (String table : tables) {
                try (PreparedStatement pst = conn.prepareStatement("DELETE FROM " + table + " WHERE UserID = ?")) {
                    pst.setString(1, selectedUserID);
                    pst.executeUpdate();
                }
            }

            conn.commit(); // If all deletions succeed

            JOptionPane.showMessageDialog(null, "All records for UserID " + selectedUserID + " deleted successfully.");

            // UI Reset
            loadUserIDs();
            clearAllFields();
            disableAllListFields();
            list_savechanges.setEnabled(false);

        } catch (Exception e) {
            try {
                if (conn != null) {
                    conn.rollback(); // Rollback on failure
                }
            } catch (SQLException se) {
                System.err.println("Rollback failed: " + se.getMessage());
            }
            JOptionPane.showMessageDialog(null, "Error deleting records: " + e.getMessage());
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                System.err.println("Error closing connection: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_list_deleteMouseClicked

    private void list_modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_modifyActionPerformed

    }//GEN-LAST:event_list_modifyActionPerformed

    private void list_modifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_modifyMouseClicked
        list_firstname.setEditable(true);
        list_lastname.setEditable(true);
        list_dateofbirth.setEditable(true);
        list_address.setEditable(true);
        list_contactnumber.setEditable(true);
        list_emailaddress.setEditable(true);
        list_accountnumber.setEditable(true);
        list_accountname.setEditable(true);
        list_govidnumber.setEditable(true);
        list_password.setEditable(true);
        list_datehired.setEditable(true);
        list_managername.setEditable(true);

        // Enable combo boxes
        list_sex.setEnabled(true);
        list_civilstatus.setEnabled(true);
        list_month.setEnabled(true);
        list_year.setEnabled(true);
        list_bankname.setEnabled(true);
        list_governmentID.setEnabled(true);
        list_department.setEnabled(true);

        // Enable the Save Changes button
        list_savechanges.setEnabled(true);
        list_modify.setEnabled(false);
    }//GEN-LAST:event_list_modifyMouseClicked

    private void list_perminuterateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_perminuterateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_perminuterateActionPerformed

    private void list_dailyrateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_dailyrateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_dailyrateActionPerformed

    private void list_dateofbirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_dateofbirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_dateofbirthActionPerformed

    private void list_governmentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_governmentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_governmentIDActionPerformed

    private void list_banknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_banknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_banknameActionPerformed

    private void list_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_yearActionPerformed

    private void list_monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_monthActionPerformed

    private void list_sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_sexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_sexActionPerformed

    private void list_departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_departmentActionPerformed

    private void list_jobpositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_jobpositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_jobpositionActionPerformed

    private void list_empstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_empstatusActionPerformed

    }//GEN-LAST:event_list_empstatusActionPerformed

    private void list_generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_generateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_generateActionPerformed

    private void navigation_payrollmoduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navigation_payrollmoduleMouseClicked
        new ADM_PaymentHistory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navigation_payrollmoduleMouseClicked

    private void navigation_createaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navigation_createaccountMouseClicked
        // TODO add your handling code here:
        new ADM_AddEMP().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navigation_createaccountMouseClicked

    private void navigation_viewaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navigation_viewaccountMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_navigation_viewaccountMouseClicked

    private void list_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADM_ListEmp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADM_ListEmp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADM_ListEmp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADM_ListEmp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADM_ListEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountnameTXT_LABEL;
    private javax.swing.JLabel accountnumberTXT_LABEL;
    private javax.swing.JLabel bankDetail_LABEL;
    private javax.swing.JLabel banknameTXT_LABEL;
    private javax.swing.JLabel credits;
    private javax.swing.JLabel currenttimee;
    private javax.swing.JLabel dailyrateTXT_LABEL;
    private javax.swing.JLabel deptTXT_LABEL;
    private javax.swing.JLabel empstatusTXT_LABEL;
    private javax.swing.JLabel firstnameTXT_LABEL;
    private javax.swing.JLabel govIDTXT_LABEL;
    private javax.swing.JLabel govidnumberTXT_LABEL;
    private javax.swing.JLabel govidnumberTXT_LABEL1;
    private javax.swing.JLabel hourlyrateTXT_LABEL;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel jobpositionTXT_LABEL;
    private javax.swing.JLabel lastnameTXT_LABEL;
    private javax.swing.JPanel left_panel;
    private javax.swing.JTextField list_accountname;
    private javax.swing.JTextField list_accountnumber;
    private javax.swing.JTextField list_address;
    private javax.swing.JComboBox<String> list_bankname;
    private javax.swing.JTextField list_basicsalary;
    private javax.swing.JComboBox<String> list_civilstatus;
    private javax.swing.JTextField list_contactnumber;
    private javax.swing.JTextField list_dailyrate;
    private javax.swing.JTextField list_datehired;
    private javax.swing.JTextField list_dateofbirth;
    private javax.swing.JButton list_delete;
    private javax.swing.JComboBox<String> list_department;
    private javax.swing.JTextField list_emailaddress;
    private javax.swing.JComboBox<String> list_empstatus;
    private javax.swing.JTextField list_firstname;
    private javax.swing.JButton list_generate;
    private javax.swing.JComboBox<String> list_governmentID;
    private javax.swing.JTextField list_govidnumber;
    private javax.swing.JTextField list_hourlyrate;
    private javax.swing.JComboBox<String> list_jobposition;
    private javax.swing.JTextField list_lastname;
    private javax.swing.JTextField list_managername;
    private javax.swing.JButton list_modify;
    private javax.swing.JComboBox<String> list_month;
    private javax.swing.JTextField list_password;
    private javax.swing.JTextField list_perminuterate;
    private javax.swing.JButton list_savechanges;
    private javax.swing.JComboBox<String> list_sex;
    private javax.swing.JComboBox<String> list_useridcombobox;
    private javax.swing.JComboBox<String> list_year;
    private javax.swing.JLabel monthTXT_LABEL;
    private javax.swing.JLabel navigation_createaccount;
    private javax.swing.JLabel navigation_payrollmodule;
    private javax.swing.JLabel navigation_viewaccount;
    private javax.swing.JLabel notes;
    private javax.swing.JLabel perminuterateTXT_LABEL;
    private javax.swing.JLabel perminuterateTXT_LABEL1;
    private javax.swing.JLabel return_banktransferpage;
    private javax.swing.JLabel sexTXT_LABEL;
    private javax.swing.JLabel sexTXT_LABEL1;
    private javax.swing.JLabel sexTXT_LABEL2;
    private javax.swing.JLabel sexTXT_LABEL3;
    private javax.swing.JLabel sexTXT_LABEL4;
    private javax.swing.JLabel sexTXT_LABEL5;
    private javax.swing.JLabel sexTXT_LABEL6;
    private javax.swing.JLabel sexTXT_LABEL7;
    private javax.swing.JLabel useridTXT_LABEL;
    private javax.swing.JLabel yearTXT_LABEL;
    // End of variables declaration//GEN-END:variables
}
