/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import static defaultpackage.PaySlip.connectDb;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.text.DecimalFormat;

/**
 *
 * @author danie
 */
public class EnterID_ForgetPass extends javax.swing.JFrame {

    Connection conn;
    private String latestUserID;

    /**
     * Creates new form EnterID_ForgetPass
     */
    public EnterID_ForgetPass() {

        this.conn = connectDb();

        initComponents();
        setLocationRelativeTo(null);
        restrictPhoneNumberInput();
        setResizable(false); // ✅ Prevents window resizing
        setExtendedState(JFrame.NORMAL); // ✅ Ensures window stays at default state

        ImageIcon logo = new ImageIcon("C:\\Users\\danie\\Downloads\\PS_FinalLogo.png"); // ✅ Update with correct file location
        setIconImage(logo.getImage());

        setTitle("Payroll Swift"); // ✅ Custom window title
    }

    private void restrictPhoneNumberInput() {
        AbstractDocument document = (AbstractDocument) phonenumber_field.getDocument();
        document.setDocumentFilter(new DocumentFilter() {
            @Override
            public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
                if (string == null) {
                    return;
                }

                // Allow only numbers and limit to 11 digits
                if ((fb.getDocument().getLength() + string.length()) <= 11 && string.matches("\\d+")) {
                    super.insertString(fb, offset, string, attr);
                }
            }

            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                if (text == null) {
                    return;
                }

                // Allow only numbers and limit to 11 digits
                if ((fb.getDocument().getLength() - length + text.length()) <= 11 && text.matches("\\d+")) {
                    super.replace(fb, offset, length, text, attrs);
                }
            }

            @Override
            public void remove(FilterBypass fb, int offset, int length) throws BadLocationException {
                super.remove(fb, offset, length);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        subtitle = new javax.swing.JLabel();
        idnumbertxt = new javax.swing.JLabel();
        phonenumber_txt = new javax.swing.JLabel();
        submitbutton = new javax.swing.JButton();
        returntologin_btn = new javax.swing.JLabel();
        phonenumber_field = new javax.swing.JTextField();
        idnumber_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AYROLL WIFT (2) (1).png"))); // NOI18N
        jLabel6.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Smart & Secure Payroll Management");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6))
                .addGap(83, 83, 83))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        title.setBackground(new java.awt.Color(0, 153, 153));
        title.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        title.setForeground(new java.awt.Color(0, 102, 102));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Help Us Confirm It’s You");

        subtitle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        subtitle.setForeground(new java.awt.Color(0, 0, 0));
        subtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitle.setText("Provide your ID and phone number to proceed with password reset.");

        idnumbertxt.setBackground(new java.awt.Color(0, 0, 0));
        idnumbertxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        idnumbertxt.setForeground(new java.awt.Color(0, 0, 0));
        idnumbertxt.setText("ID Number");

        phonenumber_txt.setBackground(new java.awt.Color(0, 0, 0));
        phonenumber_txt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        phonenumber_txt.setForeground(new java.awt.Color(0, 0, 0));
        phonenumber_txt.setText("Phone Number");

        submitbutton.setBackground(new java.awt.Color(0, 102, 102));
        submitbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitbutton.setForeground(new java.awt.Color(255, 255, 255));
        submitbutton.setText("Submit");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        returntologin_btn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        returntologin_btn.setForeground(new java.awt.Color(0, 102, 102));
        returntologin_btn.setText("Return to Login");
        returntologin_btn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        returntologin_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returntologin_btnMouseClicked(evt);
            }
        });

        phonenumber_field.setBackground(new java.awt.Color(255, 255, 255));
        phonenumber_field.setForeground(new java.awt.Color(0, 0, 0));
        phonenumber_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenumber_fieldActionPerformed(evt);
            }
        });

        idnumber_field.setBackground(new java.awt.Color(255, 255, 255));
        idnumber_field.setForeground(new java.awt.Color(0, 0, 0));
        idnumber_field.setToolTipText("");
        idnumber_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idnumber_fieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(title))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(subtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(submitbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(idnumbertxt)
                            .addComponent(phonenumber_txt)
                            .addComponent(phonenumber_field)
                            .addComponent(idnumber_field)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(returntologin_btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitle)
                .addGap(24, 24, 24)
                .addComponent(idnumbertxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idnumber_field, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(phonenumber_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phonenumber_field, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(returntologin_btn)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        // Get the entered ID number and phone number
        String idNumber = idnumber_field.getText().trim();
        String phoneNumber = phonenumber_field.getText().trim();

        // Check if either field is empty
        if (idNumber.isEmpty() || phoneNumber.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Both ID Number and Phone Number are required.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check if ID exists in the PersonalData table
        try {
            String checkIdSql = "SELECT * FROM PersonalData WHERE UserID = ?";
            PreparedStatement pst = conn.prepareStatement(checkIdSql);
            pst.setString(1, idNumber);
            ResultSet rs = pst.executeQuery();

            if (!rs.next()) {
                // ID does not exist
                JOptionPane.showMessageDialog(this, "The ID number does not exist.", "ID Not Found", JOptionPane.ERROR_MESSAGE);
                rs.close();
                pst.close();
                return;
            }

            rs.close();
            pst.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Show a confirmation dialog to verify the entered information
        int confirmation = JOptionPane.showConfirmDialog(this,
                "Please confirm the following information:\n\nID Number: " + idNumber + "\nPhone Number: " + phoneNumber,
                "Confirm Information",
                JOptionPane.YES_NO_OPTION);

        // If the user selects "Yes", proceed to the ForgotPassword page
        if (confirmation == JOptionPane.YES_OPTION) {
            this.dispose();
            new ForgotPassword(idNumber, phoneNumber).setVisible(true); // Pass ID and phone number to ForgotPassword
        }
    }//GEN-LAST:event_submitbuttonActionPerformed

    private void returntologin_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returntologin_btnMouseClicked
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_returntologin_btnMouseClicked

    private void phonenumber_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenumber_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenumber_fieldActionPerformed

    private void idnumber_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idnumber_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idnumber_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterID_ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterID_ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterID_ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterID_ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterID_ForgetPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idnumber_field;
    private javax.swing.JLabel idnumbertxt;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField phonenumber_field;
    private javax.swing.JLabel phonenumber_txt;
    private javax.swing.JLabel returntologin_btn;
    private javax.swing.JButton submitbutton;
    private javax.swing.JLabel subtitle;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
