/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defaultpackage;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.text.DecimalFormat;

/**
 *
 * @author danie
 */
public class PaySlip extends javax.swing.JFrame {

    Connection conn;
    private String latestUserID;

    /**
     * Creates new form PaySlip
     */
    public PaySlip(Connection conn) {

        this.conn = connectDb();

        initComponents();

        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false); // ✅ Prevents window resizing
        setExtendedState(JFrame.NORMAL); // ✅ Ensures window stays at default state

        ImageIcon logo = new ImageIcon("C:\\Users\\danie\\Downloads\\PS_FinalLogo.png"); // ✅ Update with correct file location
        setIconImage(logo.getImage());

        setTitle("Payroll Swift"); // ✅ Custom window title

        loadPayPeriodsForLatestUser();
        printpayslip.setEnabled(false);

    }

    public static Connection connectDb() {
        try {
            Class.forName("org.sqlite.JDBC");  // Make sure you have the SQLite JDBC driver in your project
            String url = "jdbc:sqlite:C:/Users/danie/OneDrive/Documents/NetBeansProjects/PayrollModule_2_Copy/Payroll.db";
            return java.sql.DriverManager.getConnection(url);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Database connection failed: " + e.getMessage());
            return null;
        }
    }

    private void loadPayPeriodsForLatestUser() {
        try {
            // Step 1: Get latest logged-in UserID
            String sqlLatestUser = "SELECT UserID FROM Login ORDER BY LoginTime DESC LIMIT 1";
            PreparedStatement pstUser = conn.prepareStatement(sqlLatestUser);
            ResultSet rsUser = pstUser.executeQuery();

            if (rsUser.next()) {
                latestUserID = rsUser.getString("UserID"); // Store it as a class-level variable
            } else {
                JOptionPane.showMessageDialog(null, "No recent user login found.");
                return;
            }

            rsUser.close();
            pstUser.close();

            // Step 2: Populate payperiod_combobox
            payperiod_combobox.removeAllItems(); // Clear current items

            String sqlPeriods = "SELECT PeriodCombobox FROM PaySlip WHERE UserID = ? ORDER BY PeriodCombobox DESC";
            PreparedStatement pstPeriods = conn.prepareStatement(sqlPeriods);
            pstPeriods.setString(1, latestUserID);
            ResultSet rsPeriods = pstPeriods.executeQuery();

            while (rsPeriods.next()) {
                payperiod_combobox.addItem(rsPeriods.getString("PeriodCombobox"));
            }

            rsPeriods.close();
            pstPeriods.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error loading pay periods: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        credits = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        printpayslip = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        basicsalaryTXT_LABEL = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        earningsTXT_LABEL = new javax.swing.JLabel();
        earningsamountTXT_LABEL = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        deductionsTXT_LABEL = new javax.swing.JLabel();
        deductionsamountTXT_LABEL = new javax.swing.JLabel();
        overtimepayTXT_LABEL = new javax.swing.JLabel();
        allowancesTXT_LABEL = new javax.swing.JLabel();
        incentivesTXT_LABEL = new javax.swing.JLabel();
        commissionsTXT_LABEL = new javax.swing.JLabel();
        totalearningsTXT_LABEL = new javax.swing.JLabel();
        absencesTXT_LABEL = new javax.swing.JLabel();
        latesundertimeTXT_LABEL = new javax.swing.JLabel();
        unpaidTXT_LABEL = new javax.swing.JLabel();
        othersTXT_LABEL = new javax.swing.JLabel();
        SSSTXT_LABEL = new javax.swing.JLabel();
        philhealthTXT_LABEL = new javax.swing.JLabel();
        pagibigTXT_LABEL = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        totaldeductionsTXT_LABEL = new javax.swing.JLabel();
        netpayTXT_LABEL = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        basicsalary_field = new javax.swing.JLabel();
        overtimepay_field = new javax.swing.JLabel();
        allowances_field = new javax.swing.JLabel();
        incentives_field = new javax.swing.JLabel();
        commissions_field = new javax.swing.JLabel();
        totalearnings_field = new javax.swing.JLabel();
        absences_field = new javax.swing.JLabel();
        latesundertime_field = new javax.swing.JLabel();
        unpaidleave_field = new javax.swing.JLabel();
        others_field = new javax.swing.JLabel();
        sss_field = new javax.swing.JLabel();
        philhealth_field = new javax.swing.JLabel();
        pagibig_field = new javax.swing.JLabel();
        totaldeductions_field = new javax.swing.JLabel();
        netpay_field = new javax.swing.JLabel();
        paymentdateTXT_LABEL = new javax.swing.JLabel();
        banknameTXT_LABEL = new javax.swing.JLabel();
        bankaccnameTXT_LABEL = new javax.swing.JLabel();
        bankaccnumberTXT_LABEL = new javax.swing.JLabel();
        paymentdate_field = new javax.swing.JLabel();
        bankname_field = new javax.swing.JLabel();
        bankaccountname_field = new javax.swing.JLabel();
        bankaccountnumber_field = new javax.swing.JLabel();
        paymentmethodTXT_LABEL = new javax.swing.JLabel();
        paymentmethod_field = new javax.swing.JLabel();
        nameTXT_LABEL = new javax.swing.JLabel();
        employeeIDTXT_LABEL = new javax.swing.JLabel();
        jobpositionTXT_LABEL = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        payperiodTXT_LABEL = new javax.swing.JLabel();
        companyname = new javax.swing.JLabel();
        name_field = new javax.swing.JLabel();
        empID_field = new javax.swing.JLabel();
        jobposition_field = new javax.swing.JLabel();
        department_field = new javax.swing.JLabel();
        payperiod_field = new javax.swing.JLabel();
        workddays_field = new javax.swing.JLabel();
        payslipTXT_LABEL = new javax.swing.JLabel();
        departmentTXT_LABEL1 = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        location2 = new javax.swing.JLabel();
        workeddaysTXT_LABEL = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        payperiod_combobox = new javax.swing.JComboBox<>();
        payperiod_title = new javax.swing.JLabel();
        payperiod_title1 = new javax.swing.JLabel();
        generate = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AYROLL WIFT (2) (3).png"))); // NOI18N
        jLabel4.setText(" ");

        credits.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        credits.setForeground(new java.awt.Color(255, 255, 255));
        credits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        credits.setText("© 2025 Payroll Swift");

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Access and review your payslips"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("for all pay periods. This section"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("provides a detailed breakdown of"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("your earnings, deductions, and "); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("net pay for each period."); // NOI18N

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));

        printpayslip.setBackground(new java.awt.Color(0, 51, 51));
        printpayslip.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        printpayslip.setForeground(new java.awt.Color(255, 255, 255));
        printpayslip.setText("Print PaySlip");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(credits, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(printpayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(printpayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(credits)
                .addGap(21, 21, 21))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        basicsalaryTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        basicsalaryTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        basicsalaryTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        basicsalaryTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        basicsalaryTXT_LABEL.setText("Basic Salary");

        jPanel9.setBackground(new java.awt.Color(0, 102, 102));

        earningsTXT_LABEL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        earningsTXT_LABEL.setForeground(new java.awt.Color(255, 255, 255));
        earningsTXT_LABEL.setText("Earnings");

        earningsamountTXT_LABEL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        earningsamountTXT_LABEL.setForeground(new java.awt.Color(255, 255, 255));
        earningsamountTXT_LABEL.setText("Amount");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(earningsTXT_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(earningsamountTXT_LABEL)
                .addGap(59, 59, 59))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(earningsTXT_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(earningsamountTXT_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(0, 102, 102));

        deductionsTXT_LABEL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deductionsTXT_LABEL.setForeground(new java.awt.Color(255, 255, 255));
        deductionsTXT_LABEL.setText("Deductions");

        deductionsamountTXT_LABEL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deductionsamountTXT_LABEL.setForeground(new java.awt.Color(255, 255, 255));
        deductionsamountTXT_LABEL.setText("Amount");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(deductionsTXT_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(deductionsamountTXT_LABEL)
                .addGap(54, 54, 54))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(deductionsTXT_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deductionsamountTXT_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );

        overtimepayTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        overtimepayTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        overtimepayTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        overtimepayTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        overtimepayTXT_LABEL.setText("Overtime Pay");

        allowancesTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        allowancesTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        allowancesTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        allowancesTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        allowancesTXT_LABEL.setText("Allowances");

        incentivesTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        incentivesTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        incentivesTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        incentivesTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        incentivesTXT_LABEL.setText("Incentives");

        commissionsTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        commissionsTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        commissionsTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        commissionsTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        commissionsTXT_LABEL.setText("Commissions");

        totalearningsTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        totalearningsTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        totalearningsTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        totalearningsTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalearningsTXT_LABEL.setText("Total Earnings");

        absencesTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        absencesTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        absencesTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        absencesTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        absencesTXT_LABEL.setText("Absences");

        latesundertimeTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        latesundertimeTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        latesundertimeTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        latesundertimeTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        latesundertimeTXT_LABEL.setText("Lates/Undertime");

        unpaidTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        unpaidTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        unpaidTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        unpaidTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        unpaidTXT_LABEL.setText("Unpaid Leave");

        othersTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        othersTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        othersTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        othersTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        othersTXT_LABEL.setText("Others");

        SSSTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        SSSTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        SSSTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        SSSTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SSSTXT_LABEL.setText("SSS");

        philhealthTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        philhealthTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        philhealthTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        philhealthTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        philhealthTXT_LABEL.setText("PhilHealth");

        pagibigTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        pagibigTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        pagibigTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        pagibigTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pagibigTXT_LABEL.setText("Pag-IBIG");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        totaldeductionsTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        totaldeductionsTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        totaldeductionsTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        totaldeductionsTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totaldeductionsTXT_LABEL.setText("Total Deductions");

        netpayTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        netpayTXT_LABEL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        netpayTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        netpayTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        netpayTXT_LABEL.setText("Net Pay");

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        basicsalary_field.setBackground(new java.awt.Color(0, 0, 0));
        basicsalary_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        basicsalary_field.setForeground(new java.awt.Color(0, 0, 0));
        basicsalary_field.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        basicsalary_field.setText("0.00");

        overtimepay_field.setBackground(new java.awt.Color(0, 0, 0));
        overtimepay_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        overtimepay_field.setForeground(new java.awt.Color(0, 0, 0));
        overtimepay_field.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        overtimepay_field.setText("0.00");

        allowances_field.setBackground(new java.awt.Color(0, 0, 0));
        allowances_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        allowances_field.setForeground(new java.awt.Color(0, 0, 0));
        allowances_field.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        allowances_field.setText("0.00");

        incentives_field.setBackground(new java.awt.Color(0, 0, 0));
        incentives_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        incentives_field.setForeground(new java.awt.Color(0, 0, 0));
        incentives_field.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        incentives_field.setText("0.00");

        commissions_field.setBackground(new java.awt.Color(0, 0, 0));
        commissions_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        commissions_field.setForeground(new java.awt.Color(0, 0, 0));
        commissions_field.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        commissions_field.setText("0.00");

        totalearnings_field.setBackground(new java.awt.Color(0, 0, 0));
        totalearnings_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        totalearnings_field.setForeground(new java.awt.Color(0, 0, 0));
        totalearnings_field.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalearnings_field.setText("0.00");

        absences_field.setBackground(new java.awt.Color(0, 0, 0));
        absences_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        absences_field.setForeground(new java.awt.Color(0, 0, 0));
        absences_field.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        absences_field.setText("0.00");

        latesundertime_field.setBackground(new java.awt.Color(0, 0, 0));
        latesundertime_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        latesundertime_field.setForeground(new java.awt.Color(0, 0, 0));
        latesundertime_field.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        latesundertime_field.setText("0.00");

        unpaidleave_field.setBackground(new java.awt.Color(0, 0, 0));
        unpaidleave_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        unpaidleave_field.setForeground(new java.awt.Color(0, 0, 0));
        unpaidleave_field.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unpaidleave_field.setText("0.00");

        others_field.setBackground(new java.awt.Color(0, 0, 0));
        others_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        others_field.setForeground(new java.awt.Color(0, 0, 0));
        others_field.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        others_field.setText("0.00");

        sss_field.setBackground(new java.awt.Color(0, 0, 0));
        sss_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        sss_field.setForeground(new java.awt.Color(0, 0, 0));
        sss_field.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sss_field.setText("0.00");

        philhealth_field.setBackground(new java.awt.Color(0, 0, 0));
        philhealth_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        philhealth_field.setForeground(new java.awt.Color(0, 0, 0));
        philhealth_field.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        philhealth_field.setText("0.00");

        pagibig_field.setBackground(new java.awt.Color(0, 0, 0));
        pagibig_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        pagibig_field.setForeground(new java.awt.Color(0, 0, 0));
        pagibig_field.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pagibig_field.setText("0.00");

        totaldeductions_field.setBackground(new java.awt.Color(0, 0, 0));
        totaldeductions_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        totaldeductions_field.setForeground(new java.awt.Color(0, 0, 0));
        totaldeductions_field.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totaldeductions_field.setText("0.00");

        netpay_field.setBackground(new java.awt.Color(0, 0, 0));
        netpay_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        netpay_field.setForeground(new java.awt.Color(0, 0, 0));
        netpay_field.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        netpay_field.setText("0.00");

        paymentdateTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        paymentdateTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        paymentdateTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        paymentdateTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        paymentdateTXT_LABEL.setText("Payment Date                        :");

        banknameTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        banknameTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        banknameTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        banknameTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        banknameTXT_LABEL.setText("Bank Name                            :");

        bankaccnameTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        bankaccnameTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bankaccnameTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        bankaccnameTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bankaccnameTXT_LABEL.setText("Bank Account Name              :");

        bankaccnumberTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        bankaccnumberTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bankaccnumberTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        bankaccnumberTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bankaccnumberTXT_LABEL.setText("Bank Account  #                    :");

        paymentdate_field.setBackground(new java.awt.Color(0, 0, 0));
        paymentdate_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        paymentdate_field.setForeground(new java.awt.Color(0, 0, 0));
        paymentdate_field.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        paymentdate_field.setText(" ");

        bankname_field.setBackground(new java.awt.Color(0, 0, 0));
        bankname_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bankname_field.setForeground(new java.awt.Color(0, 0, 0));
        bankname_field.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bankname_field.setText("  ");

        bankaccountname_field.setBackground(new java.awt.Color(0, 0, 0));
        bankaccountname_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bankaccountname_field.setForeground(new java.awt.Color(0, 0, 0));
        bankaccountname_field.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bankaccountname_field.setText("  ");

        bankaccountnumber_field.setBackground(new java.awt.Color(0, 0, 0));
        bankaccountnumber_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bankaccountnumber_field.setForeground(new java.awt.Color(0, 0, 0));
        bankaccountnumber_field.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bankaccountnumber_field.setText("  ");

        paymentmethodTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        paymentmethodTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        paymentmethodTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        paymentmethodTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        paymentmethodTXT_LABEL.setText("Payment Method                     :");

        paymentmethod_field.setBackground(new java.awt.Color(0, 0, 0));
        paymentmethod_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        paymentmethod_field.setForeground(new java.awt.Color(0, 0, 0));
        paymentmethod_field.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        paymentmethod_field.setText("  ");

        nameTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        nameTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        nameTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        nameTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameTXT_LABEL.setText("Name                                           :");

        employeeIDTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        employeeIDTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        employeeIDTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        employeeIDTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        employeeIDTXT_LABEL.setText("Employee ID                                 :");

        jobpositionTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        jobpositionTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jobpositionTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        jobpositionTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jobpositionTXT_LABEL.setText("Job Position                                 :");

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);

        payperiodTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        payperiodTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        payperiodTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        payperiodTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        payperiodTXT_LABEL.setText("Pay Period                        :");

        companyname.setBackground(new java.awt.Color(0, 0, 0));
        companyname.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        companyname.setForeground(new java.awt.Color(0, 0, 0));
        companyname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        companyname.setText("VertexTech Solutions Inc.");

        name_field.setBackground(new java.awt.Color(0, 0, 0));
        name_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        name_field.setForeground(new java.awt.Color(0, 0, 0));
        name_field.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name_field.setText(" ");

        empID_field.setBackground(new java.awt.Color(0, 0, 0));
        empID_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        empID_field.setForeground(new java.awt.Color(0, 0, 0));
        empID_field.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        empID_field.setText(" ");

        jobposition_field.setBackground(new java.awt.Color(0, 0, 0));
        jobposition_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jobposition_field.setForeground(new java.awt.Color(0, 0, 0));
        jobposition_field.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jobposition_field.setText(" ");

        department_field.setBackground(new java.awt.Color(0, 0, 0));
        department_field.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        department_field.setForeground(new java.awt.Color(0, 0, 0));
        department_field.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        department_field.setText("  ");

        payperiod_field.setBackground(new java.awt.Color(0, 0, 0));
        payperiod_field.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        payperiod_field.setForeground(new java.awt.Color(0, 0, 0));
        payperiod_field.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        payperiod_field.setText("  ");

        workddays_field.setBackground(new java.awt.Color(0, 0, 0));
        workddays_field.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        workddays_field.setForeground(new java.awt.Color(0, 0, 0));
        workddays_field.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        workddays_field.setText(" ");

        payslipTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        payslipTXT_LABEL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        payslipTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        payslipTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        payslipTXT_LABEL.setText("PaySlip");

        departmentTXT_LABEL1.setBackground(new java.awt.Color(0, 0, 0));
        departmentTXT_LABEL1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        departmentTXT_LABEL1.setForeground(new java.awt.Color(0, 0, 0));
        departmentTXT_LABEL1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        departmentTXT_LABEL1.setText("Department                      :");

        location.setBackground(new java.awt.Color(0, 0, 0));
        location.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        location.setForeground(new java.awt.Color(0, 0, 0));
        location.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        location.setText("123 Sampaguita Street, Brgy. San Isidro,");

        location2.setBackground(new java.awt.Color(0, 0, 0));
        location2.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        location2.setForeground(new java.awt.Color(0, 0, 0));
        location2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        location2.setText("Lipa City, Batangas, 4217, Philippines");

        workeddaysTXT_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        workeddaysTXT_LABEL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        workeddaysTXT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        workeddaysTXT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        workeddaysTXT_LABEL.setText("Worked Days                    :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bankaccnameTXT_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(bankaccnumberTXT_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paymentdateTXT_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(banknameTXT_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(paymentdate_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bankaccountname_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bankaccountnumber_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(bankname_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(netpay_field, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(netpayTXT_LABEL))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(paymentmethodTXT_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(paymentmethod_field, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(commissionsTXT_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(incentivesTXT_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(allowancesTXT_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(overtimepayTXT_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(basicsalaryTXT_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(totalearningsTXT_LABEL)
                                .addGap(18, 18, 18)))
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalearnings_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(commissions_field, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(incentives_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(allowances_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(overtimepay_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(basicsalary_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(othersTXT_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(unpaidTXT_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(latesundertimeTXT_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SSSTXT_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(philhealthTXT_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(absencesTXT_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totaldeductionsTXT_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pagibigTXT_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pagibig_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(philhealth_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sss_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(others_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(unpaidleave_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(latesundertime_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(absences_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totaldeductions_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(nameTXT_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(employeeIDTXT_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                                .addComponent(jobpositionTXT_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                    .addGap(12, 12, 12)
                                                    .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(empID_field, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jobposition_field, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGap(12, 12, 12)
                                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(payperiodTXT_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(departmentTXT_LABEL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(workeddaysTXT_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(department_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(payperiod_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(workddays_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(298, 298, 298)
                                .addComponent(location2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(304, 304, 304)
                                .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(325, 325, 325)
                                .addComponent(companyname, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(392, 392, 392)
                                .addComponent(payslipTXT_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(payslipTXT_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(companyname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(location2)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameTXT_LABEL)
                            .addComponent(name_field))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeeIDTXT_LABEL)
                            .addComponent(empID_field))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jobpositionTXT_LABEL)
                            .addComponent(jobposition_field)))
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(department_field)
                            .addComponent(departmentTXT_LABEL1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(payperiodTXT_LABEL)
                            .addComponent(payperiod_field))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(workddays_field)
                            .addComponent(workeddaysTXT_LABEL))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(absences_field)
                        .addGap(14, 14, 14)
                        .addComponent(latesundertime_field)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(unpaidleave_field)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(others_field)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sss_field)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(philhealth_field)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pagibig_field)
                        .addGap(36, 36, 36)
                        .addComponent(totaldeductions_field)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(basicsalary_field)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(overtimepay_field)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(allowances_field)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(incentives_field)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(commissions_field)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(totalearnings_field)
                                                .addGap(26, 26, 26))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(basicsalaryTXT_LABEL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(overtimepayTXT_LABEL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(allowancesTXT_LABEL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(incentivesTXT_LABEL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(commissionsTXT_LABEL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(totalearningsTXT_LABEL)
                                                .addGap(27, 27, 27))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(absencesTXT_LABEL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(latesundertimeTXT_LABEL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(unpaidTXT_LABEL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(othersTXT_LABEL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(SSSTXT_LABEL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(philhealthTXT_LABEL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(pagibigTXT_LABEL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(totaldeductionsTXT_LABEL)
                                                .addGap(27, 27, 27))))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jSeparator6)
                                        .addGap(13, 13, 13)))
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(paymentdateTXT_LABEL)
                                    .addComponent(paymentdate_field))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(banknameTXT_LABEL)
                                    .addComponent(bankname_field))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bankaccnameTXT_LABEL)
                                    .addComponent(bankaccountname_field))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bankaccnumberTXT_LABEL)
                                    .addComponent(bankaccountnumber_field)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(netpayTXT_LABEL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(netpay_field)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(paymentmethod_field)
                                    .addComponent(paymentmethodTXT_LABEL)))))
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        payperiod_combobox.setBackground(new java.awt.Color(255, 255, 255));
        payperiod_combobox.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        payperiod_combobox.setForeground(new java.awt.Color(0, 0, 0));
        payperiod_combobox.setToolTipText("");
        payperiod_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payperiod_comboboxActionPerformed(evt);
            }
        });

        payperiod_title.setBackground(new java.awt.Color(0, 0, 0));
        payperiod_title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        payperiod_title.setForeground(new java.awt.Color(0, 0, 0));
        payperiod_title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        payperiod_title.setText("Pay Period");

        payperiod_title1.setBackground(new java.awt.Color(0, 0, 0));
        payperiod_title1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        payperiod_title1.setForeground(new java.awt.Color(0, 0, 0));
        payperiod_title1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        payperiod_title1.setText("RECENT PAYSLIP");

        generate.setBackground(new java.awt.Color(0, 51, 51));
        generate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        generate.setForeground(new java.awt.Color(255, 255, 255));
        generate.setText("Generate");
        generate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateMouseClicked(evt);
            }
        });
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(payperiod_title1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(payperiod_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(payperiod_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(payperiod_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(payperiod_title)
                            .addComponent(payperiod_title1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(generate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(15, 15, 15)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void payperiod_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payperiod_comboboxActionPerformed


    }//GEN-LAST:event_payperiod_comboboxActionPerformed
    private String formatAmount(ResultSet rs, String columnName) throws SQLException {
        double amount = rs.getDouble(columnName);
        DecimalFormat formatter = new DecimalFormat("#,###.00");
        return formatter.format(amount);
    }

    private void generateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateMouseClicked
        printpayslip.setEnabled(true);
        
        String selectedPeriod = (String) payperiod_combobox.getSelectedItem();

        if (selectedPeriod == null || selectedPeriod.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select a pay period.");
            return;
        }

        try {
            String sql = "SELECT * FROM PaySlip WHERE UserID = ? AND PeriodCombobox = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, latestUserID);  // You should store latestUserID as a class variable
            pst.setString(2, selectedPeriod);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                // Set fields
                name_field.setText(rs.getString("Name"));
                empID_field.setText(rs.getString("UserID"));
                jobposition_field.setText(rs.getString("JobPos"));
                department_field.setText(rs.getString("Dept"));
                payperiod_field.setText(rs.getString("PayPeriod"));
                workddays_field.setText(rs.getString("WorkDays"));

                basicsalary_field.setText(formatAmount(rs, "BasicSalary"));
                overtimepay_field.setText(formatAmount(rs, "OvertimePay"));
                allowances_field.setText(formatAmount(rs, "Allowances"));
                incentives_field.setText(formatAmount(rs, "Incentives"));
                commissions_field.setText(formatAmount(rs, "Commissions"));
                absences_field.setText(formatAmount(rs, "Absences"));
                latesundertime_field.setText(formatAmount(rs, "LatesUndertime"));
                unpaidleave_field.setText(formatAmount(rs, "UnpaidLeave"));
                others_field.setText(formatAmount(rs, "Others"));
                sss_field.setText(formatAmount(rs, "SSS"));
                philhealth_field.setText(formatAmount(rs, "Philhealth"));
                pagibig_field.setText(formatAmount(rs, "PagIBIG"));
                totalearnings_field.setText(formatAmount(rs, "TotalEarnings"));
                totaldeductions_field.setText(formatAmount(rs, "TotalDeduc"));
                netpay_field.setText(formatAmount(rs, "NetPay"));

                paymentdate_field.setText(rs.getString("PaymentDate"));
                bankname_field.setText(rs.getString("BankName"));
                bankaccountname_field.setText(rs.getString("BankAccName"));
                bankaccountnumber_field.setText(rs.getString("BankNum"));
                paymentmethod_field.setText(rs.getString("PayMethod"));
            } else {
                JOptionPane.showMessageDialog(null, "No data found for selected period.");
            }

            rs.close();
            pst.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error retrieving payslip: " + e.getMessage());
        }
    }//GEN-LAST:event_generateMouseClicked

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaySlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaySlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaySlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaySlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Connection conn = PaySlip.connectDb();  // Use the static method inside this class
                new PaySlip(conn).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SSSTXT_LABEL;
    private javax.swing.JLabel absencesTXT_LABEL;
    private javax.swing.JLabel absences_field;
    private javax.swing.JLabel allowancesTXT_LABEL;
    private javax.swing.JLabel allowances_field;
    private javax.swing.JLabel bankaccnameTXT_LABEL;
    private javax.swing.JLabel bankaccnumberTXT_LABEL;
    private javax.swing.JLabel bankaccountname_field;
    private javax.swing.JLabel bankaccountnumber_field;
    private javax.swing.JLabel banknameTXT_LABEL;
    private javax.swing.JLabel bankname_field;
    private javax.swing.JLabel basicsalaryTXT_LABEL;
    private javax.swing.JLabel basicsalary_field;
    private javax.swing.JLabel commissionsTXT_LABEL;
    private javax.swing.JLabel commissions_field;
    private javax.swing.JLabel companyname;
    private javax.swing.JLabel credits;
    private javax.swing.JLabel deductionsTXT_LABEL;
    private javax.swing.JLabel deductionsamountTXT_LABEL;
    private javax.swing.JLabel departmentTXT_LABEL1;
    private javax.swing.JLabel department_field;
    private javax.swing.JLabel earningsTXT_LABEL;
    private javax.swing.JLabel earningsamountTXT_LABEL;
    private javax.swing.JLabel empID_field;
    private javax.swing.JLabel employeeIDTXT_LABEL;
    private javax.swing.JButton generate;
    private javax.swing.JLabel incentivesTXT_LABEL;
    private javax.swing.JLabel incentives_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jobpositionTXT_LABEL;
    private javax.swing.JLabel jobposition_field;
    private javax.swing.JLabel latesundertimeTXT_LABEL;
    private javax.swing.JLabel latesundertime_field;
    private javax.swing.JLabel location;
    private javax.swing.JLabel location2;
    private javax.swing.JLabel nameTXT_LABEL;
    private javax.swing.JLabel name_field;
    private javax.swing.JLabel netpayTXT_LABEL;
    private javax.swing.JLabel netpay_field;
    private javax.swing.JLabel othersTXT_LABEL;
    private javax.swing.JLabel others_field;
    private javax.swing.JLabel overtimepayTXT_LABEL;
    private javax.swing.JLabel overtimepay_field;
    private javax.swing.JLabel pagibigTXT_LABEL;
    private javax.swing.JLabel pagibig_field;
    private javax.swing.JLabel paymentdateTXT_LABEL;
    private javax.swing.JLabel paymentdate_field;
    private javax.swing.JLabel paymentmethodTXT_LABEL;
    private javax.swing.JLabel paymentmethod_field;
    private javax.swing.JLabel payperiodTXT_LABEL;
    private javax.swing.JComboBox<String> payperiod_combobox;
    private javax.swing.JLabel payperiod_field;
    private javax.swing.JLabel payperiod_title;
    private javax.swing.JLabel payperiod_title1;
    private javax.swing.JLabel payslipTXT_LABEL;
    private javax.swing.JLabel philhealthTXT_LABEL;
    private javax.swing.JLabel philhealth_field;
    private javax.swing.JButton printpayslip;
    private javax.swing.JLabel sss_field;
    private javax.swing.JLabel totaldeductionsTXT_LABEL;
    private javax.swing.JLabel totaldeductions_field;
    private javax.swing.JLabel totalearningsTXT_LABEL;
    private javax.swing.JLabel totalearnings_field;
    private javax.swing.JLabel unpaidTXT_LABEL;
    private javax.swing.JLabel unpaidleave_field;
    private javax.swing.JLabel workddays_field;
    private javax.swing.JLabel workeddaysTXT_LABEL;
    // End of variables declaration//GEN-END:variables
}
